In [1]:
import pandas as pd

In [52]:
JB_Movies = pd.read_csv('jamesbond.csv')
JB_Movies.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [8]:
JB_Movies.set_index(keys='Film', inplace= True)

In [10]:
JB_Movies.reset_index();

In [11]:
JB_Movies.loc['Skyfall']

Year                         2012
Actor                Daniel Craig
Director               Sam Mendes
Box Office                  943.5
Budget                      170.2
Bond Actor Salary            14.5
Name: Skyfall, dtype: object

In [13]:
JB_Movies.sort_values(by='Box Office', ascending=False)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9

In [15]:
JB_Movies.loc['Skyfall',['Actor','Bond Actor Salary']]

Actor                Daniel Craig
Bond Actor Salary            14.5
Name: Skyfall, dtype: object

In [16]:
JB_Movies.loc[['Skyfall', 'Moonraker'],['Actor','Bond Actor Salary']]

                  Actor  Bond Actor Salary
Film
Skyfall    Daniel Craig               14.5
Moonraker   Roger Moore                NaN

In [17]:
JB_Movies.iloc[:7,3:]

                                 Box Office  Budget  Bond Actor Salary
Film
Dr. No                                448.8     7.0                0.6
From Russia with Love                 543.8    12.6                1.6
Goldfinger                            820.4    18.6                3.2
Thunderball                           848.1    41.9                4.7
Casino Royale                         315.0    85.0                NaN
You Only Live Twice                   514.2    59.9                4.4
On Her Majesty's Secret Service       291.5    37.3                0.6

In [19]:
JB_Movies.rename(mapper={'Year':'Release Date', 'Box Office':'Revenue'}, axis=1)

,Release Date,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [22]:
JB_Movies.nlargest(3, columns= 'Box Office')

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [26]:
column_name = JB_Movies.columns

In [30]:
JB_Movies.columns = column_name.str.replace(' ','_')

In [31]:
JB_Movies

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [38]:
JB_Movies.query('Actor == "Sean Connery"')

,Year,Actor,Director,Box_Office,Budget,Bond_Actor_Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN

In [42]:
def convert_to_strig_and_add_millions(number):
    return str(number)+ ' MILLIONS!'
JB_Movies['Box_Office'] = JB_Movies['Box_Office'].apply(convert_to_strig_and_add_millions)

In [44]:
JB_Movies['Budget'] = JB_Movies['Budget'].apply(convert_to_strig_and_add_millions)

In [61]:
def convert_to_strig_and_add_millions(number):
    return str(number) + ' MILLIONS!'

In [62]:
columns = ['Box Office', 'Budget', 'Bond Actor Salary']
for col in columns:
    JB_Movies[col] = JB_Movies[col].apply(convert_to_strig_and_add_millions)

In [63]:
JB_Movies

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,7.0 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,0.6 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,12.6 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,1.6 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,18.6 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,3.2 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
3,Thunderball,1965,Sean Connery,Terence Young,848.1 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,41.9 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,4.7 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
4,Casino Royale,1967,David Niven,Ken Hughes,315.0 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,85.0 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,nan MILLIONS! MILLIONS! MILLIONS! MILLIONS!
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,59.9 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,4.4 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,37.3 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,0.6 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,34.7 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,5.8 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,30.8 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,nan MILLIONS! MILLIONS! MILLIONS! MILLIONS!
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,27.7 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,nan MILLIONS! MILLIONS! MILLIONS! MILLIONS!
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,45.1 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,nan MILLIONS! MILLIONS! MILLIONS! MILLIONS!
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,91.5 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,nan MILLIONS! MILLIONS! MILLIONS! MILLIONS!
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,60.2 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,nan MILLIONS! MILLIONS! MILLIONS! MILLIONS!
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,86.0 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,nan MILLIONS! MILLIONS! MILLIONS! MILLIONS!
14,Octopussy,1983,Roger Moore,John Glen,373.8 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,53.9 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,7.8 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
15,A View to a Kill,1985,Roger Moore,John Glen,275.2 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,54.5 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,9.1 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,68.8 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,5.2 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,56.7 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,7.9 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,76.9 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,5.1 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,133.9 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,10.0 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,158.3 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,13.5 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,154.2 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,17.9 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,145.3 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,3.3 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,181.4 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,8.1 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,170.2 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,14.5 MILLIONS! MILLIONS! MILLIONS! MILLIONS!
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,206.3 MILLIONS! MILLIONS! MILLIONS! MILLIONS!,nan MILLIONS! MILLIONS! MILLIONS! MILLIONS!

In [64]:
JB_Movies = JB_Movies.replace({'MILLIONS! MILLIONS! MILLIONS! MILLIONS!': 'MILLIONS!'}, regex=True)

In [65]:
JB_Movies

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8 MILLIONS!,7.0 MILLIONS!,0.6 MILLIONS!
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8 MILLIONS!,12.6 MILLIONS!,1.6 MILLIONS!
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4 MILLIONS!,18.6 MILLIONS!,3.2 MILLIONS!
3,Thunderball,1965,Sean Connery,Terence Young,848.1 MILLIONS!,41.9 MILLIONS!,4.7 MILLIONS!
4,Casino Royale,1967,David Niven,Ken Hughes,315.0 MILLIONS!,85.0 MILLIONS!,nan MILLIONS!
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2 MILLIONS!,59.9 MILLIONS!,4.4 MILLIONS!
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5 MILLIONS!,37.3 MILLIONS!,0.6 MILLIONS!
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5 MILLIONS!,34.7 MILLIONS!,5.8 MILLIONS!
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3 MILLIONS!,30.8 MILLIONS!,nan MILLIONS!
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0 MILLIONS!,27.7 MILLIONS!,nan MILLIONS!
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0 MILLIONS!,45.1 MILLIONS!,nan MILLIONS!
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0 MILLIONS!,91.5 MILLIONS!,nan MILLIONS!
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4 MILLIONS!,60.2 MILLIONS!,nan MILLIONS!
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0 MILLIONS!,86.0 MILLIONS!,nan MILLIONS!
14,Octopussy,1983,Roger Moore,John Glen,373.8 MILLIONS!,53.9 MILLIONS!,7.8 MILLIONS!
15,A View to a Kill,1985,Roger Moore,John Glen,275.2 MILLIONS!,54.5 MILLIONS!,9.1 MILLIONS!
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5 MILLIONS!,68.8 MILLIONS!,5.2 MILLIONS!
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9 MILLIONS!,56.7 MILLIONS!,7.9 MILLIONS!
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5 MILLIONS!,76.9 MILLIONS!,5.1 MILLIONS!
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2 MILLIONS!,133.9 MILLIONS!,10.0 MILLIONS!
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5 MILLIONS!,158.3 MILLIONS!,13.5 MILLIONS!
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4 MILLIONS!,154.2 MILLIONS!,17.9 MILLIONS!
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5 MILLIONS!,145.3 MILLIONS!,3.3 MILLIONS!
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2 MILLIONS!,181.4 MILLIONS!,8.1 MILLIONS!
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5 MILLIONS!,170.2 MILLIONS!,14.5 MILLIONS!
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7 MILLIONS!,206.3 MILLIONS!,nan MILLIONS!

In [81]:
JB_Movies = pd.read_csv('jamesbond.csv', index_col='Film')
JB_Movies.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [76]:
def good_movie(row):
    
    actor = row[1]
    budget = row[4]
    
    if actor == 'Pierce Brosnan':
        return 'The best'
    elif actor == 'Roger Moore' and budget > 40:
        return 'Enjoyable'
    else:
        return 'I have no clue'

JB_Movies.apply(good_movie, axis= 'columns')

Film
Dr. No                             I have no clue
From Russia with Love              I have no clue
Goldfinger                         I have no clue
Thunderball                        I have no clue
Casino Royale                      I have no clue
You Only Live Twice                I have no clue
On Her Majesty's Secret Service    I have no clue
Diamonds Are Forever               I have no clue
Live and Let Die                   I have no clue
The Man with the Golden Gun        I have no clue
The Spy Who Loved Me                    Enjoyable
Moonraker                               Enjoyable
For Your Eyes Only                      Enjoyable
Never Say Never Again              I have no clue
Octopussy                               Enjoyable
A View to a Kill                        Enjoyable
The Living Daylights               I have no clue
Licence to Kill                    I have no clue
GoldenEye                                The best
Tomorrow Never Dies                      The best
The World Is Not Enough                  The best
Die Another Day                          The best
Casino Royale                      I have no clue
Quantum of Solace                  I have no clue
Skyfall                            I have no clue
Spectre                            I have no clue
dtype: object

In [83]:
directors = JB_Movies.Director.copy()
directors.head()

Film
Dr. No                   Terence Young
From Russia with Love    Terence Young
Goldfinger                Guy Hamilton
Thunderball              Terence Young
Casino Royale               Ken Hughes
Name: Director, dtype: object

In [84]:
directors['Dr. No'] = 'Otro'

In [86]:
directors.head()

Film
Dr. No                            Otro
From Russia with Love    Terence Young
Goldfinger                Guy Hamilton
Thunderball              Terence Young
Casino Royale               Ken Hughes
Name: Director, dtype: object

In [87]:
JB_Movies.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN