In [1]:
import pandas as pd

In [7]:
JB_Movies = pd.read_csv('jamesbond.csv')
JB_Movies.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [8]:
JB_Movies.set_index(keys='Film', inplace= True)

In [10]:
JB_Movies.reset_index();

In [11]:
JB_Movies.loc['Skyfall']

Year                         2012
Actor                Daniel Craig
Director               Sam Mendes
Box Office                  943.5
Budget                      170.2
Bond Actor Salary            14.5
Name: Skyfall, dtype: object

In [13]:
JB_Movies.sort_values(by='Box Office', ascending=False)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9

In [15]:
JB_Movies.loc['Skyfall',['Actor','Bond Actor Salary']]

Actor                Daniel Craig
Bond Actor Salary            14.5
Name: Skyfall, dtype: object

In [16]:
JB_Movies.loc[['Skyfall', 'Moonraker'],['Actor','Bond Actor Salary']]

                  Actor  Bond Actor Salary
Film
Skyfall    Daniel Craig               14.5
Moonraker   Roger Moore                NaN

In [17]:
JB_Movies.iloc[:7,3:]

                                 Box Office  Budget  Bond Actor Salary
Film
Dr. No                                448.8     7.0                0.6
From Russia with Love                 543.8    12.6                1.6
Goldfinger                            820.4    18.6                3.2
Thunderball                           848.1    41.9                4.7
Casino Royale                         315.0    85.0                NaN
You Only Live Twice                   514.2    59.9                4.4
On Her Majesty's Secret Service       291.5    37.3                0.6

In [19]:
JB_Movies.rename(mapper={'Year':'Release Date', 'Box Office':'Revenue'}, axis=1)

,Release Date,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN